document.write("<h1> Q1 </h1> ")
var studentName =[ "imam" , "hyder" , "ali"]
document.write(studentName)
document.write("<h1> Q2 </h1>")
document.write("A VARAISBLE NAME CAN'T CONTAIN ANY SPACE <BR>")
document.write("A VARAIBLE NAME CAN CONTAIN ONLY LETTERS , NUMBERS , DOLLAR SIGN AND UNDERSCORES <BR>")
document.write("CAPITAL LETTER IS FINE BUT BE CAREFULL  <BR>")
document.write("USE CAMELCASE IN YOUR VAR NAME  <BR>")
document.write("MAKE YOUR VAR NAME DESCRIPTIVE SO ITS EASY <BR>")
document.write("<h1> Q3 </h1>")
document.write(" <h1>RULES FOR NAMING JS VARISBLE </h1> ")
document.write("A VARAIBLE NAME CAN CONTAIN ONLY LETTERS , NUMBERS , DOLLAR SIGN AND UNDERSCORES <BR>")
document.write("VARIABLE NAME ARE CASE SENSITIVE <BR>")
document.write("VAR NAME SHOULD NO BE JS KEYWORDS <BR>")
document.write("<h1> MUHAMMAD IMAM </h1>")
document.write("<h1> CCO 117033 </h1>")